### ISSUE TITLE
Wizard opening on Step 5

### ISSUE THREAD

**Issue by vconzola** [fusor/mig-ui#122]
After creating a plan, if user selects Add plan button the wizard opens at step 5 with validation running and then shows validation success with no plan name.
![Screen Shot 2019-04-24 at 3 49 04 PM](https://user-images.githubusercontent.com/22823035/56689243-a200a180-66a8-11e9-80d1-c9a82ffeaa61.png)

**Comment by eriknelson** [comment]
Sounds like we've determined this is actually a pf4 modal bug that needs to get fixed upstream. @ibolton336 do you have a link to the issue you filed upstream so we can add it here?

**Comment by ibolton336** [comment]
I actually think the bug was fixed upstream. We just havent updated out version of PF4.

**Comment by ibolton336** [comment]
https://github.com/patternfly/patternfly-react/issues/1845
