### ISSUE TITLE
Very bad experience with self-signed clusters

### ISSUE THREAD

**Issue by eriknelson** [fusor/mig-ui#197]
Right now, in remote dev mode (and this will continue to be an issue with production builds), the app has a very bad experience with self-signed clusters. The current experience without already having accepted the CAs in your browser, makes the app appear to crash immediately on login. In order to get around this, you literally need to have your network pane open or pre-emptively visit the required endpoints and accept the certs before the app will run.

This continues to happen when you talk to a source cluster for the first time at the namespace fetch during plan creation; the browser blocks the request unless you again explicitly accept the ocp3 cluster's cert.

This is all correct and expected behavior; the browser should not let us talk to an unverified https destination unless the CA's have either been pre-registered, or ack'd by the user as acceptable. We need a solution for this:

* It's possible we might be able to detect when this failure occurs, although when I looked in the error handler, I really didn't see anything that indicated the request failed due to an unknown CA. I'm not sure how much we can improve this experience, we should investigate.
* We need documentation that explains if the certs are self signed, they *must* be registered with the browser as acceptable before the app will run.

Curious what other people's thoughts are on how to tackle this so we can have a smoother experience for self-signed clusters (or is this possibly not a large requirement, even?)

Pretty sure this will even affect the controller, we might need to add an optional field so we can pass the a self CA to the controller via secret.

**Comment by jwmatthews** [comment]
I think this issue is beyond self-signed certs, we will need to update the UI/API to allow the ability to upload a CA for each cluster.

**Comment by eriknelson** [comment]
The XHR request has almost no information about this error. The decision is to alert the user to navigate to the failed link if the error appears like a `Network Error` and accept the certificate and reload the page.
