### ISSUE TITLE
Buggy behavior on add cluster

### ISSUE THREAD

**Issue by ibolton336** [fusor/mig-ui#215]
theres still a bit of buggy behavior around the connection piece. When i add a bogus cluster, it shows up as connection failed after adding. then on refresh.. there is not icon state on the left in the data list b/c i think the controller is updating the status. 

Also, I can add duplicate clusters with the same name. Also, sometimes when i add a new cluster, it just doesnt show up in any list until i refresh.

**Comment by jwmatthews** [comment]
Also not seeing errors being reflected in webui, see below, entered 'sourceB' for the 'name' of the cluster, and didn't see an error in webui.

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Cluster.clusterregistry.k8s.io \"sourceB\" is invalid: metadata.name: Invalid value: \"sourceB\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')",
  "reason": "Invalid",
  "details": {
    "name": "sourceB",
    "group": "clusterregistry.k8s.io",
    "kind": "Cluster",
    "causes": [
      {
        "reason": "FieldValueInvalid",
        "message": "Invalid value: \"sourceB\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')",
        "field": "metadata.name"
      }
    ]
  },
  "code": 422
}

Request payload
{apiVersion: "clusterregistry.k8s.io/v1alpha1", kind: "Cluster",…}
apiVersion: "clusterregistry.k8s.io/v1alpha1"
kind: "Cluster"
metadata: {name: "sourceB", namespace: "mig"}
name: "sourceB"
namespace: "mig"
spec: {kubernetesApiEndpoints: {,…}}
kubernetesApiEndpoints: {,…}
serverEndpoints: [{clientCIDR: "0.0.0.0", serverAddress: "https://api.jwm05162019a.migration.redhat.com:6443"}]
0: {clientCIDR: "0.0.0.0", serverAddress: "https://api.jwm05162019a.migration.redhat.com:6443"}
clientCIDR: "0.0.0.0"
serverAddress: "https://api.jwm05162019a.migration.redhat.com:6443"

**Comment by ibolton336** [comment]
When adding a cluster, secret not found issue
<img width="537" alt="Screen Shot 2019-06-10 at 3 06 15 PM" src="https://user-images.githubusercontent.com/11218376/59219904-8c303880-8b91-11e9-97d1-970a5d3d886b.png">
