### ISSUE TITLE
Using the 'yarn start:remote' option, after ~2 days, Loading icons are present and not able to load data from k8s API.

### ISSUE THREAD

**Issue by jwmatthews** [fusor/mig-ui#216]
After 2-3 days of having 'yarn start:remote' up and working on UI code I've lost access to talk to k8s cluste.r . Assume a token has expired.

At a minimum we need to detect this error and report back to UI, right now I don't see any errors displayed, had to look at js console to find permissions issues.

Seeing 401 and 403 errors.

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "migclusters.migration.openshift.io is forbidden: User \"system:anonymous\" cannot list resource \"migclusters\" in API group \"migration.openshift.io\" in the namespace \"mig\"",
  "reason": "Forbidden",
  "details": {
    "group": "migration.openshift.io",
    "kind": "migclusters"
  },
  "code": 403
}

Failed to load resource: the server responded with a status of 401 ()
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}

**Comment by jwmatthews** [comment]
To work around this from the Web Developer tools I went to 'Application'.
Storage->Local Storage->http://localhost:9000

Then deleted 'currentUser'
Reloaded page and was able to login

**Comment by ibolton336** [comment]
Similar issue to #197
