### ISSUE TITLE
Source dropdown css bug

### ISSUE THREAD

**Issue by ibolton336** [fusor/mig-ui#244]
Need to address the height issue on the migsource page causing this bug
<img width="1435" alt="Screen Shot 2019-06-10 at 3 20 49 PM" src="https://user-images.githubusercontent.com/11218376/59220617-6a37b580-8b93-11e9-8c52-90b127995aed.png">

**Comment by eriknelson** [comment]
Resolved with #285 , we just needed to update PF deps to pick up fixes.
