### ISSUE TITLE
App erroring out when source selected 

### ISSUE THREAD

**Issue by ibolton336** [fusor/mig-ui#245]
<img width="1420" alt="Screen Shot 2019-06-10 at 3 22 25 PM" src="https://user-images.githubusercontent.com/11218376/59220731-ac60f700-8b93-11e9-8b2d-a234295dba24.png">

**Comment by eriknelson** [comment]
This occurs when the host cluster is selected. I think we want to gracefully handle this bug, but also filter out the host from being available as a source cluster unless that's a primary use case that we want to support.
