### ISSUE TITLE
Need to sanitize names

### ISSUE THREAD

**Issue by eriknelson** [fusor/mig-ui#251]
The names that the users enter are being used directly as k8s object names. k8s has a set of validations that follow "DNS" name rules. Things like uppercase letters are going to 422 if posted, along with a number of other rules. We have a couple options:

* Sanitize the names so we lowercase it, replace unacceptable chars etc.
* Reject unacceptable names

I don't think the second option is very friendly, and I recall preferring the first option in previous projects for this reason.

**Comment by alexander-demichev** [comment]
We may need second approach when name contains unicode characters like this `˚¬˜˚˜` or not english letters

**Comment by eriknelson** [comment]
@alexander-demichev we should consider if those are even k8s compatible. If not they need to be validated and rejected.

**Comment by eriknelson** [comment]
@Danil-Grigorev has submitted some fairly strong form validation, and I'm reconsidering the need for this issue. We can open at a later time if this is desired.
