### ISSUE TITLE
Address issues that require us to pin, "@patternfly/react-core" to 3.16.4

### ISSUE THREAD

**Issue by jwmatthews** [fusor/mig-ui#269]
We are currently pinned to 3.16.4 for "@patternfly/react-core"

One of the issues I hit in past was related to our modal and passing in an argument to onClose().

https://github.com/fusor/mig-ui/blob/master/src/app/common/components/ConfirmModal.tsx#L7

Below issue is related and has been closed on patternfly side.
https://github.com/patternfly/patternfly-react/issues/2233

**Comment by eriknelson** [comment]
According to this comment, the `isConfirmed` field was never actually used for anything, so it should be safe to just delete it from our usage and we should still compile. I'm not sure what patternfly version we'd like to move up to, but we should upgrade to that and determine there haven't been any regressions before considering this closed.

> Your isConfirmed: any was never being used, so just remove it or open an issue for Modal if you want the type to be (event: MouseEvent) => void.

**Comment by eriknelson** [comment]
Resolved by #285, although it revealed some dependency conflicts between our `@emotion` styles and theirs that aren't likely to be resolved unless PF4 updates their `@emotion` dep. Ian and I have decided to avoid this altogether with #287 as a solution.
