### ISSUE TITLE
Add CORS config details to docs for 3.x & 4.x clusters once determined

### ISSUE THREAD

**Issue by eriknelson** [fusor/mig-ui#273]
This specifically refers to the officially supported CORS API in 4.x.

**Comment by eriknelson** [comment]
#272

**Comment by eriknelson** [comment]
Added 3.x instructions to README.

**Comment by jwmatthews** [comment]
I think we should expand the 3.x instructions, provide explicit example of what a change would look like along with command to restart the processes needed (For example I was unsure if  'master-restart api' was sufficient, or if we also needed  'master-restart controllers')


Example of adding 'migration-mig.apps.cluster-jwm0706ocp4a.jwm0706ocp4a.mg.dog8code.com'

https://github.com/fusor/mig-ui/blob/master/deploy/README.md#ocp3-cors-configuration


```
# vim /etc/origin/master/master-config.yaml

...
corsAllowedOrigins:
- (?i)//127\.0\.0\.1(:|\z)
- (?i)//localhost(:|\z)
- (?i)//192\.168\.0\.189(:|\z)
- (?i)//kubernetes\.default(:|\z)
- (?i)//master\.jwm0705ocp3a\.mg\.dog8code\.com(:|\z)
- (?i)//kubernetes(:|\z)
- (?i)//openshift\.default(:|\z)
- (?i)//master1\.jwm0705ocp3a\.internal(:|\z)
- (?i)//openshift\.default\.svc(:|\z)
- (?i)//172\.30\.0\.1(:|\z)
- (?i)//openshift\.default\.svc\.cluster\.local(:|\z)
- (?i)//kubernetes\.default\.svc(:|\z)
- (?i)//kubernetes\.default\.svc\.cluster\.local(:|\z)
- (?i)//openshift(:|\z)
- (?i)//migration-mig\.apps\.cluster-jwm0706ocp4a\.jwm0706ocp4a\.mg\.dog8code\.com(:|\z)
```

```
# time master-restart api
2

real	0m1.202s
user	0m0.045s
sys	0m0.057s

```

**Comment by eriknelson** [comment]
CORS is now handled by the operator and can be safely ignored.
