### ISSUE TITLE
In tsconfig update allowJS so it is processing both js(x)/ts(x) files

### ISSUE THREAD

**Issue by jwmatthews** [fusor/mig-ui#299]
To guard against potential future issues with hybrid usage of js(x) and ts(x) files in same project, update 'allowJs' to true.

currently commented out, defaults to 'false'
https://github.com/fusor/mig-ui/blob/master/tsconfig.json#L7

> 
    // "allowJs": true,                       /* Allow javascript files to be compiled. */

**Comment by eriknelson** [comment]
We're only building the front-end with typescript, so it's not a hybrid app. We can discuss the other js files that exist, but I think that's a distinct issue. Closing this and actually setting `allowJs` explicitly to true. #337 renames the only "js" file that was part of src.
