### ISSUE TITLE
Re-examine webpack configuration to refactor shared duplication between dev/prod configs

### ISSUE THREAD

**Issue by jwmatthews** [fusor/mig-ui#301]
Suggestion to refactor the webpack configurations, extract the common pieces so that dev/prod are using shared common pieces instead of copy/paste of duplicates.

Similar for dev/prod app HTML templates

**Comment by eriknelson** [comment]
We don't expect those HTML template to change at all, the duplication is basically just the HTML boilerplate, so that's why there are two.

I also don't think there's enough duplication in the webpack files, which aren't likely to change, to really warrant this refactoring or a coupling of the two.
