### ISSUE TITLE
Revisit usage of ts-jest to ensure full coverage of all files if more js files are added in future

### ISSUE THREAD

**Issue by jwmatthews** [fusor/mig-ui#302]

**Comment by eriknelson** [comment]
Not sure what this means, what js files is this referring to? The only js file I see that's part of the front-end build is the helper file, which is 3 lines and could probably be eliminated.

Is the complaint the rest of the surrounding js?

**Comment by eriknelson** [comment]
Closing this as #337 enforces ts within the front-end app.
