### ISSUE TITLE
Consider using semver patterns for dependencies

### ISSUE THREAD

**Issue by jwmatthews** [fusor/mig-ui#306]
"not using semver patterns for most deps, which means deps can stay on the same version for longer periods of time (and reducing the usability of Yarn upgrade-interactive command), which results in big-bang dep version updates, which is dangerous (multiple smaller updates are always better and safer)"

**Comment by eriknelson** [comment]
This was due to a bot that used to manage our deps that was disabled. +1 on this issue, i've gone through to correctly version all of our deps.
