### ISSUE TITLE
Reconsider establishing a consistent convention for filenames, example:  HomeComponent.tsx vs StatusIcon.tsx

### ISSUE THREAD

**Issue by jwmatthews** [fusor/mig-ui#308]

**Comment by eriknelson** [comment]
We've settled on NOT using a Component suffix if they live within a component dir. We have an issue that we closed for this reason. I'd like to have specific issues filed for specific files that doen't follow that convention. Would also not be a bad idea to put these code conventions in to a contributing doc.
