### ISSUE TITLE
After adding a cluster the UI reports Connection Failed until I refresh the page

### ISSUE THREAD

**Issue by jmontleon** [fusor/mig-ui#314]
I added a cluster, successfully testing the connection in the process. When I'm returned to the main page it says:

1 Connected
1 Connection failed

After refreshing the page:
2 Connected
0 Connection failed

**Comment by jmontleon** [comment]
The same happens when adding a repository

**Comment by eriknelson** [comment]
Fixed as of #340. It's on a 4 second polling timer.
