### ISSUE TITLE
Need to improve error message for CORS issues:   Seen during MigPlan with Namespace discovery, /api/v1/namespaces

### ISSUE THREAD

**Issue by jwmatthews** [fusor/mig-ui#317]
I had a mistake in how I configured corsAllowedOrigins in my source cluster.
Resulted in an error with namespace discovery.

This issue is about the error displayed was misleading, I realize we have a hard time to decipher the specifics...but we need to find a way to improve as current UXD is poor.

Sample error message:

> A certificate error has occurred, likely due to the usage of self signed certificates in one of the clusters. Please try to visit the failed url and accept the CA:https://master.clustername.mg.dog8code.com/api/v1/namespaces
> 
> The correct way to address this is to install your self CA into your browser.
> 
> NOTE: The contents of the resulting page may report "unauthorized". This is expected. After accepting the certificate, please reload the app.

And from network tab of browser traffic

```

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "namespaces is forbidden: User \"system:anonymous\" cannot list namespaces at the cluster scope: no RBAC policy matched",
  "reason": "Forbidden",
  "details": {
    "kind": "namespaces"
  },
  "code": 403
}

```

**Comment by eriknelson** [comment]
@jmatthews do you have a suggestion for how we can improve this message?

**Comment by jmatthews** [comment]
Wrong jmatthews.

**Comment by eriknelson** [comment]
apologies! thank you for the heads up.
@jwmatthews
