### ISSUE TITLE
Add a validation on MigPlan name: Starting with a number is not allowed, example '0710a' used for plan name resulted in error 

### ISSUE THREAD

**Issue by jwmatthews** [fusor/mig-ui#319]
Let's add a check in webui to ensure names entered by the user match:
regex used for validation is 
`'[a-z]([-a-z0-9]*[a-z0-9])?'`

Related to https://github.com/fusor/mig-controller/issues/190

**Comment by eriknelson** [comment]
Related #251, they're slightly different issues but could be knocked out by the same PR.

**Comment by eriknelson** [comment]
I'm confused on this one, because I'm able to create a plan called `0710a`, and that passes the regex that was specified here. I'm curious if there was something like whitespace in the name.
