### ISSUE TITLE
Consider increasing styling width when we render MigMigration phase statuses

### ISSUE THREAD

**Issue by jwmatthews** [fusor/mig-ui#329]
<img width="1526" alt="Screen Shot 2019-07-11 at 1 39 21 PM" src="https://user-images.githubusercontent.com/206875/61072463-588b3d00-a3e1-11e9-8664-38463e543658.png">

You can see here how there is more room to expand but the 
  'e' from 'Stage' 
  'd' from EnsureAnnotationsDeleted

are wrapped to next line

**Comment by jwmatthews** [comment]
Another view

Looks like there is some more room for MigrationTable we could expand into?

<img width="1237" alt="Screen Shot 2019-07-11 at 1 47 15 PM" src="https://user-images.githubusercontent.com/206875/61072995-75744000-a3e2-11e9-8c70-b6dd072296dc.png">

**Comment by jwmatthews** [comment]
Notice how Failed is displayed one character per line in below

<img width="1643" alt="Screen Shot 2019-07-29 at 10 02 52 PM" src="https://user-images.githubusercontent.com/206875/62094921-ba0a3300-b24c-11e9-89be-4986e707844f.png">

**Comment by eriknelson** [comment]
Fixed in #434, Derek bumped width from 6->9. Should fit much cleaner.
