### ISSUE TITLE
Feature: Implement status improvements

### ISSUE THREAD

**Issue by eriknelson** [fusor/mig-ui#331]
As of 07/12's demo, we managed to get in the raw phases, but we need a high level document that describes all the possible states, how they transition, what the user facing text should be, and perhaps try to bucket them into "steps" (feedback from the demo today).

There are a lot of issues filed related to this, but I'm seeing this issue as the parent issue that captures the overall definition of exactly how we should handle status reporting.

**Comment by jwmatthews** [comment]
A thought to consider...
Push the logic into controller for telling the UI about Step X of Y.
So...the UI displays a 'status_description' field from the CR.
The 'status_description' field would yield info such as
  'Step 1 of 20, Created'
  'Step 2 of 20, Started'
 ...
   'Step 20 of 20, Completed'

Thinking we'd capture:
  { "current_step": "1", "total_steps": "20", "description": "Created"}

Related definitions in mig-controller
https://github.com/fusor/mig-controller/blob/migration-with-pv-copy/pkg/controller/migmigration/task.go#L12-L39

**Comment by jortel** [comment]
run tests

**Comment by jortel** [comment]
Agreed that the progress information needs to be explicitly reported by the controller rather than derived by the UI and should be decoupled from _phase_.  I envision something simple (much as @jwmatthews has):
```
{
  completed: <int>
  total: <int>
}
```

The _Running_ condition `Reason` already includes the _step_ (currently the raw phase) so I'm reluctant to include it in the progress as well but open to being convinced.

**Comment by jortel** [comment]
The follow proposal has been discussed.

The controller will _bucket_ phases into courser grained _steps_ used to provide progress reporting.

The steps:
- Prepare
- BackupApplications
- Quiesce
- BackupPVs
- RestorePVs
- RestoreApplications
- Cleanup

The progress information will be provided in the _Running_ condition.  The `Reason` will continue to reflect the current _step_.  The `Message` will include the _step_ name and the _n_ `/`_total_.
For example:

```
Type:      Running
Category:  Advisory
Status:    True
Reason:    BackupApplications
Message:   Running: (2/7) BackupApplications
Last Transition Time:  2019-07-17T16:04:32Z
```

**Comment by djwhatle** [comment]
I personally like the specification of `BackupApplications`, and `BackupPersistentVolumes` (or perhaps `BackupPVs`).

**Comment by eriknelson** [comment]
#434
