### ISSUE TITLE
Implement error status icons for migration detailed view

### ISSUE THREAD

**Issue by Danil-Grigorev** [fusor/mig-ui#355]
![image (5)](https://user-images.githubusercontent.com/32226600/61553143-063dc200-aa5a-11e9-9bd3-1b823a18de8f.png)

Icons does not represent the actual state of migration or stage. Other resources view, such as cluster and migstorage representations use a set of green and red icons to notify the user about it's state.

**Comment by eriknelson** [comment]
Fixed by #434
