### ISSUE TITLE
Add popovers to cluster and storage wizards

### ISSUE THREAD

**Issue by alexander-demichev** [fusor/mig-ui#356]
We need to add popovers to fields like Cluster name, Url, etc. for giving user a hint of what should be there

**Comment by ibolton336** [comment]
@vconzola @eriknelson It would be helpful to come up with some copy for these popovers. Maybe this is something that we can discuss in our meeting this week.

**Comment by mturley** [comment]
@eriknelson @ibolton336 would you guys mind giving me perms on this repo so I can assign myself to issues? I think I'm going to grab this one

**Comment by eriknelson** [comment]
@mturley added!

**Comment by vconzola** [comment]
I don't think we need embedded help for cluster name because it's user generated. Here's a mockup with popover text for the add/edit cluster modal.
![add cluster popovers](https://user-images.githubusercontent.com/22823035/74542207-1bf06880-4f11-11ea-9b4b-be9b0c232c0a.png)
