### ISSUE TITLE
Error message disappears in about 5 seconds

### ISSUE THREAD

**Issue by alexander-demichev** [fusor/mig-ui#358]
Error message on top of the screen disappears in about 5 seconds, it will be hard to read if message is long.

<img width="1348" alt="Screenshot 2019-07-22 at 11 59 05" src="https://user-images.githubusercontent.com/20123872/61619853-54301100-ac78-11e9-83d7-b8e8101e9ac5.png">

**Comment by eriknelson** [comment]
Does it make sense to have an error timeout at all? It's a call-to-action we want the user to see and respond to. We also probably want them to manually dismiss it.

**Comment by eriknelson** [comment]
I'm going to bump this to 30s for now.
