### ISSUE TITLE
s3 bucket region can be a select input

### ISSUE THREAD

**Issue by alexander-demichev** [fusor/mig-ui#360]
There is a limited amount of regions so having this field as select input can be a better UX.
<img width="541" alt="Screenshot 2019-07-22 at 12 31 36" src="https://user-images.githubusercontent.com/20123872/61622209-0538aa80-ac7d-11e9-9a65-9d341ad1c64f.png">

**Comment by eriknelson** [comment]
We should run this by UX; there is more to consider here if other S3 providers are considered.

**Comment by jwmatthews** [comment]
We need to remember that the S3 workflow needs to support any S3 compatible API, so not just AWS.

Need to look to see what the S3 API uses and see if region is broken out as an input, or should this be more generic and have a full Path to a bucket.

Agree though this needs some attention

**Comment by eriknelson** [comment]
After some discussion, this **must** be a freeform text field due to our desire to handle both AWS and custom S3 backends that may not be part of the standard AWS set.
