### ISSUE TITLE
Dropdowns/popovers/selections flash and disappear inside of tables

### ISSUE THREAD

**Issue by ibolton336** [fusor/mig-ui#378]
Need to optimize rerenders that are created by the background polling. This is causing some user experience headaches

**Comment by eriknelson** [comment]
I wonder if we could be smarter about pushing updates somehow, like hashing the results and only updating if something has changed.

**Comment by eriknelson** [comment]
The current thinking on this one is that the data flowing into the react-table component is causing the flicker. We're evaluating how we might be able to fix this with react-table hooks, or if we should move to the pf table.
