### ISSUE TITLE
Storage class shown on UI does not match that on the source cluster

### ISSUE THREAD

**Issue by rpattath** [fusor/mig-ui#393]
On the source cluster:
root@ip-172-31-35-9: ~/go/src/github.com/fusor/mig-operator # oc get pv
NAME      CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                      STORAGECLASS   REASON    AGE
pv1       100Gi      RWO,ROX,RWX    Retain           Available                              ceph-rbd                 31m
pv2       100Gi      RWO,ROX,RWX    Retain           Available                              ceph-rbd                 31m
pv3       100Gi      RWO,ROX,RWX    Retain           Available                              ceph-rbd                 31m
pv4       100Gi      RWO,ROX,RWX    Retain           Available                              ceph-rbd                 31m
pv5       100Gi      RWO,ROX,RWX    Retain           Available                              ceph-rbd                 31m
pv6       100Gi      RWO,ROX,RWX    Retain           Available                              ceph-rbd                 31m
pv7       100Gi      RWO,ROX,RWX    Retain           Bound       nginx-example/nginx-logs   ceph-rbd                 31m
pv8       100Gi      RWO,ROX,RWX    Retain           Available                              ceph-rbd                 31m
pv9       100Gi      RWO,ROX,RWX    Retain           Available                              ceph-rbd                 31m

Attaching screenshot of the UI.

root@ip-172-31-61-189: ~/go/src/github.com/fusor/mig-operator # oc get MigPlan -n mig
NAME       AGE
testplan   12m
root@ip-172-31-61-189: ~/go/src/github.com/fusor/mig-operator # oc describe MigPlan -n mig
Name:         testplan
Namespace:    mig
Labels:       <none>
Annotations:  touch: d16b1658-709f-40ef-b9b6-4299e1c512c8
API Version:  migration.openshift.io/v1alpha1
Kind:         MigPlan
Metadata:
  Creation Timestamp:  2019-07-29T21:07:43Z
  Generation:          5
  Resource Version:    25952
  Self Link:           /apis/migration.openshift.io/v1alpha1/namespaces/mig/migplans/testplan
  UID:                 e8067074-b244-11e9-8c1f-023583962bae
Spec:
  Dest Mig Cluster Ref:
    Name:       host
    Namespace:  mig
  Mig Storage Ref:
    Name:       testrepo
    Namespace:  mig
  Namespaces:
    nginx-example
  Src Mig Cluster Ref:
    Name:       rpattath-3-nfscopy
    Namespace:  mig
Status:
  Conditions:
    Category:              Required
    Last Transition Time:  2019-07-29T21:08:28Z
    Message:               The `persistentVolumes` list has been updated with discovered PVs.
    Reason:                Done
    Status:                True
    Type:                  PvsDiscovered
    Category:              Required
    Last Transition Time:  2019-07-29T21:08:29Z
    Message:               The storage resources have been created.
    Status:                True
    Type:                  StorageEnsured
    Category:              Required
    Last Transition Time:  2019-07-29T21:08:30Z
    Message:               The migration registry resources have been created.
    Status:                True
    Type:                  RegistriesEnsured
    Category:              Required
    Last Transition Time:  2019-07-29T21:08:30Z
    Message:               The migration plan is ready.
    Status:                True
    Type:                  Ready
Events:                    <none>
root@ip-172-31-61-189: ~/go/src/github.com/fusor/mig-operator # oc get MigPlan -n mig -o yaml
apiVersion: v1
items:
- apiVersion: migration.openshift.io/v1alpha1
  kind: MigPlan
  metadata:
    annotations:
      touch: d16b1658-709f-40ef-b9b6-4299e1c512c8
    creationTimestamp: "2019-07-29T21:07:43Z"
    generation: 5
    name: testplan
    namespace: mig
    resourceVersion: "25952"
    selfLink: /apis/migration.openshift.io/v1alpha1/namespaces/mig/migplans/testplan
    uid: e8067074-b244-11e9-8c1f-023583962bae
  spec:
    destMigClusterRef:
      name: host
      namespace: mig
    migStorageRef:
      name: testrepo
      namespace: mig
    namespaces:
    - nginx-example
    srcMigClusterRef:
      name: rpattath-3-nfscopy
      namespace: mig
  status:
    conditions:
    - category: Required
      lastTransitionTime: "2019-07-29T21:08:28Z"
      message: The `persistentVolumes` list has been updated with discovered PVs.
      reason: Done
      status: "True"
      type: PvsDiscovered
    - category: Required
      lastTransitionTime: "2019-07-29T21:08:29Z"
      message: The storage resources have been created.
      status: "True"
      type: StorageEnsured
    - category: Required
      lastTransitionTime: "2019-07-29T21:08:30Z"
      message: The migration registry resources have been created.
      status: "True"
      type: RegistriesEnsured
    - category: Required
      lastTransitionTime: "2019-07-29T21:08:30Z"
      message: The migration plan is ready.
      status: "True"
      type: Ready
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

![Screenshot from 2019-07-29 17-08-14](https://user-images.githubusercontent.com/26095715/62085026-a6e56c00-b228-11e9-9e0e-9568acbd5a85.png)

**Comment by sseago** [comment]
What storageclasses are available on the destination cluster? I'm guessing that it's choosing gp2 as the initial value because it's the default storageclass and because a storageclass with the same provisioner as ceph-rbd on the source cluster is not available on the destination.

**Comment by sseago** [comment]
The output of both of the following commands would help to determine if whether what you're seeing is correct:
`oc get storageclasses` (on both src and dest clusters)
`oc get migcluster -n mig -o yaml` (on the controller cluster to pull the list of storageclasses that the controller knows about for both src and dest clusters)

**Comment by jwmatthews** [comment]
I'm able to replicate this with a pair of clusters deployed tonight.

The issue is that 'Step 3' of the wizard is intended to display information about the 'Source'.
In this case, there is no storageclass used on the source side as the source PV is a NFS PV 


Looking at Source Side

```
$ oc get storageclass
No resources found.

$ oc get pvc mssql-pvc -n mssql-persistent -o yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2019-07-29T23:28:58Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: mssql-container
  name: mssql-pvc
  namespace: mssql-persistent
  resourceVersion: "28798"
  selfLink: /api/v1/namespaces/mssql-persistent/persistentvolumeclaims/mssql-pvc
  uid: a3a5776a-b258-11e9-9b8d-0a003cad64ac
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: vol99
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  phase: Bound




$ oc get pv vol99 -o yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2019-07-29T20:57:29Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: vol99
  resourceVersion: "28796"
  selfLink: /api/v1/persistentvolumes/vol99
  uid: 7a46eead-b243-11e9-ad5d-0a003cad64ac
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: mssql-pvc
    namespace: mssql-persistent
    resourceVersion: "28794"
    uid: a3a5776a-b258-11e9-9b8d-0a003cad64ac
  nfs:
    path: /srv/nfs/user-vols/vol99
    server: support1.jwm0729ocp3a.mg.dog8code.com
  persistentVolumeReclaimPolicy: Recycle
status:
  phase: Bound
```

Looking at destination side
```
$ oc get storageclasses
NAME            PROVISIONER             AGE
gp2 (default)   kubernetes.io/aws-ebs   5h3m


$ oc get migplan test01 -n mig -o yaml
apiVersion: migration.openshift.io/v1alpha1
kind: MigPlan
metadata:
  annotations:
    touch: e6e0bbc1-91b9-42c6-945b-117f230738a5
  creationTimestamp: "2019-07-30T01:45:06Z"
  generation: 2
  name: test01
  namespace: mig
  resourceVersion: "88764"
  selfLink: /apis/migration.openshift.io/v1alpha1/namespaces/mig/migplans/test01
  uid: a865b483-b26b-11e9-be86-0ad7604b88d6
spec:
  destMigClusterRef:
    name: host
    namespace: mig
  namespaces:
  - mssql-persistent
  persistentVolumes:
  - capacity: 10Gi
    name: vol99
    pvc:
      accessModes:
      - ReadWriteOnce
      name: mssql-pvc
      namespace: mssql-persistent
    selection:
      storageClass: gp2
    supported:
      actions:
      - copy
      - move
  srcMigClusterRef:
    name: jwm0729ocp3a
    namespace: mig
status:
  conditions:
  - category: Critical
    lastTransitionTime: "2019-07-30T01:45:06Z"
    message: The `migStorageRef` must reference a `migstorage`.
    reason: NotSet
    status: "True"
    type: InvalidStorageRef
  - category: Required
    lastTransitionTime: "2019-07-30T01:45:07Z"
    message: The `persistentVolumes` list has been updated with discovered PVs.
    reason: Done
    status: "True"
    type: PvsDiscovered
  - category: Error
    lastTransitionTime: "2019-07-30T01:45:07Z"
    message: PV in `persistentVolumes` [vol99] has an unsupported `action`.
    reason: NotDone
    status: "True"
    type: PvInvalidAction
```

**Comment by eriknelson** [comment]
Confirmed this is a bug; it's setting the table value during PV discovery to be the default selection intended for the **target** cluster to be the value here, rather than the source storageClass in use associated with the source PV. @sseago, I don't see any field on the MigPlan that indicates what storageClass is in use by the source PV (if any). I assume it's probably omitted because there is none. Let's catch up in slack so I can correctly fill this field.

**Comment by sseago** [comment]
@eriknelson Source storage class is in the storageClass field of the persistentVolumes entry (if there is any). As @jwmatthews pointed out, for src cluster we may or may not have a storageclass.
