### ISSUE TITLE
The remote cluster is connected but the migration plan creation fails

### ISSUE THREAD

**Issue by sergiordlr** [fusor/mig-ui#417]
Hello,

When creating a migration plan using a remote cluster that has no "https://" at the beginning of the URL, the cluster is validated properly, but the migration plan fails when we choose the remote cluster.

What I did:
1) configure a storage.
2) configure a remote cluster with this url "master.ocp3.qe.devcluster.openshift.com:443". No https// at the beginning of the url.
3) click add plan
4) Use "testplan" as the name. and Clik "Next"
5) select my cluster in the "Source Cluster" field.

What I expected: 
- To be able to fill in the rest of the migration form and create the full migration plan. Or the cluster to say that it cannot connect if the url needs "https://" when I am adding the source cluster.

What it happened:
- The cluster is shown as connected properly, but as soon as I select the "Source Cluster" I am redirected to /cert-error path and an error in the connection is displayed.

If I edit the source cluster and I prepend "https://" to the url, I can create the plan with no problem.

Please, tell me if you need more information.

BR.

**Comment by eriknelson** [comment]
We have a URL validation in place now that requires the URL to have its protocol.
