### ISSUE TITLE
Add Plan button is missing from empty state view

### ISSUE THREAD

**Issue by jwmatthews** [fusor/mig-ui#457]
See below screen shot, when I see the big grey '+' I assume it should be clickable and we can create a new plan from doing so.  Is that the intent and we need to wire it up, or does the '+' server another purpose?

<img width="1646" alt="Screen Shot 2019-08-16 at 7 48 15 AM" src="https://user-images.githubusercontent.com/206875/63165730-46ad4300-bffa-11e9-98b2-3f2ada1324cc.png">

**Comment by eriknelson** [comment]
![image](https://user-images.githubusercontent.com/410933/63166386-43b35200-bffc-11e9-8999-0c57b7029a22.png)

This is how it's mocked, it's just an icon, but looks like we're missing the button.
