### ISSUE TITLE
capitalization

### ISSUE THREAD

**Issue by apinnick** [fusor/mig-ui#463]
"Add cluster" - Change to "Add Cluster", to be consistent with "Add Repository" and "Add Plan"

"Add Repository" window: "Url" not all caps. Is this intentional?

**Comment by vconzola** [comment]
@apinnick New PatternFly guidance is that all text elements should be sentence-style (except product names and proper nouns), so it's actually "Add Repository" and "Add Plan" that should be changed to "Add repository" and "Add plan".

**Comment by apinnick** [comment]
Oh my. I'll update the documentation. Thanks for the update. That will solve a lot of problems (like whether to capitalize prepositions) and it will make the UI more consistent.

"URL" is an acronym, so it's exempt from the sentence case directive because acronyms have their own capitalization convention.

**Comment by apinnick** [comment]
In Add migration plan > Persistent Volumes, the dropdown list for the persistent volume options ("copy"/"move") is lower case. Should be capitalized.
