### ISSUE TITLE
Provide user feedback when a plan is in Closing

### ISSUE THREAD

**Issue by jwmatthews** [fusor/mig-ui#483]
When we delete a plan from UI, the UI will
 - Perform a close
 - Wait for close
 - Perform a delete

This issue is to track work to make it very clear that when we delete a plan, the plan transitions to a closing state, then will be deleting.  

Thinking something where we visually saying Closing... in the status and show a spinner or dots moving something to indicate a task is in progress.

Also, we will want to make the close best effort, if the close fails we will want to ensure we still delete the Plan.

**Comment by eriknelson** [comment]
Fixed by #504
