### ISSUE TITLE
white page at point 4

### ISSUE THREAD

**Issue by jmontleon** [fusor/mig-ui#511]
@spagno filed an issue against operator that I believe would be better tracked against UI:

Hi,
i did the setup on a ocp 4.1 cluster and on a ocp 3.11 cluster and it worked good.
When I migrate a project without pvc no problem at all but when I try to migrate a projet with pvc, at point 4 "Storage Class" I get a white page.
This happens with firefox 68.0 and chrome 76.0.3809.100 on fedora core 30

Even if I got a white page, the Plan has been created but I cannot delete it with chrome

regards

**Comment by jwmatthews** [comment]
@djwhatle is this similar to issue you saw Friday with 3.10 -> 3.11 migration.

**Comment by jwmatthews** [comment]
@spagno is it possible to get the javascript console logs so we can help to see what went wrong?

**Comment by jwmatthews** [comment]
We ran into a similar issue on Friday when our destination class lacked a storage class.
Below PR fixed the issue.
https://github.com/fusor/mig-ui/pull/514

**Comment by eriknelson** [comment]
I believe #514 fixes this, going to close this. Please re-open if this continues to show up.
