### ISSUE TITLE
Clicking “View all …” doesn’t expand related data list item

### ISSUE THREAD

**Issue by vconzola** [fusor/mig-ui#547]
Clicking the "View all..." links on the cards at the top of the main page in the UI should expand the corresponding section below and close any others that are open. Currently, clicking those links doesn't do anything.
![Screen Shot 2019-09-09 at 2 50 34 PM](https://user-images.githubusercontent.com/22823035/64558149-3e9ea580-d311-11e9-9775-c922772ed905.png)

**Comment by ibolton336** [comment]
Closed via #545
