### ISSUE TITLE
Icons on main page cards should only appear when the value is > 0

### ISSUE THREAD

**Issue by vconzola** [fusor/mig-ui#550]
Colored status icons appear even when value is 0, so there is no contrast in these conditions. For example, only show failed icon if there are >=1 failures.  See [mockup.](https://marvelapp.com/66cj5ga/screen/60982350)

**Comment by ibolton336** [comment]
![image](https://user-images.githubusercontent.com/11218376/64563551-a5c25700-d31d-11e9-9805-1eac639e57ac.png)

Is this what we are looking for?

**Comment by vconzola** [comment]
@ibolton336 Yup, exactly. Thanks.
