### ISSUE TITLE
Migration plan table - UX enhancements

### ISSUE THREAD

**Issue by vconzola** [fusor/mig-ui#589]
1. Replace existing icon with the PF [migration icon](https://www.patternfly.org/v4/design-guidelines/styles/icons).
2. Remove the volume icons from the PVs column. The icon is very heavy and visually distracting.
3. User should be able to click on the number as well as the icon to expand a table row. See PF [Compound Expandable table] (https://www.patternfly.org/v4/documentation/react/components/table/) documentation.
4. Use sentence style capitalization for column headers.
5. Migration start and end times should follow PF recommended [date and time](https://www.patternfly.org/v4/design-guidelines/content/grammar-and-terminology#date-and-time) format.
6. For running stages/migrations display "In progress" for the end time.

**Comment by vconzola** [comment]
See this [mockup:](https://marvelapp.com/project/4334729/screen/61792840/comments/)

**Comment by ibolton336** [comment]
> See this [mockup.](https://marvelapp.com/project/4334729/screen/61792840/comments/)

Can't see this mockup. Seems to be a permissions issue. Able to see this one ok: https://marvelapp.com/44ef860/screen/61197120

**Comment by ibolton336** [comment]
Are we sure we want to remove the icons in the plans card for in progress & complete? Looks odd IMO 
<img width="1395" alt="Screen Shot 2019-10-08 at 3 18 54 PM" src="https://user-images.githubusercontent.com/11218376/66426066-0dcc9180-e9df-11e9-822e-7feb7526f929.png">

**Comment by vconzola** [comment]
@ibolton336 Crap! It does look odd. I think partly because the numbers aren't vertically aligned. I was trying to avoid showing the error icon when no errors are present. Let me ask for a few other folks opinions. Maybe we just don't show the state at all if the count is zero? But then we have bigass cards that are mostly empty. Ugh! I can't wait until we can ditch the cards altogether.

**Comment by ibolton336** [comment]
> @ibolton336 Crap! It does look odd. I think partly because the numbers aren't vertically aligned. I was trying to avoid showing the error icon when no errors are present. Let me ask for a few other folks opinions. Maybe we just don't show the state at all if the count is zero? But then we have bigass cards that are mostly empty. Ugh! I can't wait until we can ditch the cards altogether.

Sounds good let me know what the verdict is

**Comment by vconzola** [comment]
@ibolton336 MShaks came up with a really clever idea - always show the icons but deemphasize the icon and the text when the count is zero. Like this:
![image](https://user-images.githubusercontent.com/22823035/66600275-31c0dc00-eb73-11e9-80d1-56e9009df61c.png)
The colors you'll want to use for the icons and text are:
![image](https://user-images.githubusercontent.com/22823035/66600327-4d2be700-eb73-11e9-9202-6aa84df67993.png)

**Comment by ibolton336** [comment]
<img width="1438" alt="Screen Shot 2019-10-14 at 7 46 37 PM" src="https://user-images.githubusercontent.com/11218376/66789860-7625e200-eebb-11e9-8e10-5c09e9e6ad5b.png">
Added update for the disabled modifier - still will need a seperate issue for adding additional plan states in card view
