### ISSUE TITLE
Re-evaluate using reduxsauce due to type concerns

### ISSUE THREAD

**Issue by eriknelson** [fusor/mig-ui#62]
Currently fixing a bug (#61) that's a direct result of us opting out of typescript type checking. Basically all the error dispatches were passing in an Error type, when the reducer was expecting a string. Is it possible to continue using `reduxsauce` to generate our action creators and make them strongly typed? If not, I think we should re-evaluate how we want to write our action creators, and possibly drop reduxsauce.

**Comment by ibolton336** [comment]
I'm ok with dropping redux sauce

**Comment by eriknelson** [comment]
Honestly I like the convenience it offers a lot, it'd be nice if there was a typed approach available.
