### ISSUE TITLE
[non-admin] Push namespace discovery to controller

### ISSUE THREAD

**Issue by dymurray** [fusor/mig-ui#646]
With the non-admin work we will not hitting the `projects` API from the web UI any longer. Instead we will offload the namespace discovery to the controller. For more information on how this will work, see here: https://github.com/fusor/mig-controller/issues/391.

What's important from the UI side is that the UI will be reading the list of available namespaces off the `migcluster` object instead of hitting the `projects` API. Additionally, if no list of namespaces is found, then it is safe to assume this is not an OCP cluster. If that is the case then the user will be expected to enter in a list of namespace into the UI. This will require a change in the wizard.

**Comment by eriknelson** [comment]
https://github.com/fusor/mig-ui/pull/640 https://github.com/fusor/mig-controller/pull/380
These PRs introduce a separate "discovery service" that runs alongside the controller and provides meta information about the various clusters, including namespaces that can be moved. Putting discovered namespaces onto MigClusters was determined to be a non-starter during the design of this work, the discovery service should accomplish what we're looking to do here I think, but in a more sustainable way (for example, it's actually paged). Let's catch up more about that.

**Comment by dymurray** [comment]
@eriknelson Ah thank you I wasn't aware of that. I will sync up with Jeff on this as well. If this is already being handled in other mig-ui work please feel free to close this.

**Comment by eriknelson** [comment]
So the UI up to now has always done a LIST namespaces, it never talked to the project API. I'm fairly sure the discovery service is doing something similar. In any case, we can't get around the "ACL filtered list" problem. If the desire is to get a subset of namespaces that exist in the cluster that the user has admin to, the discovery service is going to have the same problem; it can't get that list, especially if it's just a kubernetes cluster.

All that to say, we still might need to require the user to manually enter their namespaces if we have absolutely no way to get a list of namespaces that a specific user has access to *and no more*.

**Comment by eriknelson** [comment]
I'm going to consider the scope of this issue as the title states, that the namespace discovery should be driven by the discovery service. There's going to be a lot of work that comes out of the non-admin design that I want to break up into clearly defined and tractable issues rather than one umbrella issue. I'll take a work item to file those as the non-admin conversation progresses.
