### ISSUE TITLE
"Migrate" window text

### ISSUE THREAD

**Issue by apinnick** [fusor/mig-ui#670]
Screenshot: https://github.com/fusor/mig-agnosticd/blob/master/demos/2019_RHTE/labs/screenshots/lab5/cam-quiesce.png

"Halting" is not normally used in OpenShift docs. "Stopping" is the preferred term.
I suggest changing the text in this window:

Applications [or pods or processes] on the source cluster are stopped before migration begins and restarted after migration. Persistent volumes associated with the migrated projects are moved or copied to the target cluster, according to the migration plan.

Check box: Do not stop applications on the source cluster during migration.

**Comment by eriknelson** [comment]
Thank you for the report @apinnick, we'll get this updated for our 1.2 release.
